created the Aromas component + added a dictionary for the product page
SoftRyzen-internship/13candles-frontend pull request #100
Opened 2023-11-20 00:48 UTC by Bardjur

2023-11-20 13:12 UTC, nadiakhoptiuk requested changes

2023-11-20 13:12 UTC, nadiakhoptiuk commented on components/Aromas/Aromas.tsx
> +        <span className="font-semibold">{notes} </span>
тут двокрапку пропустив

2023-11-20 13:12 UTC, nadiakhoptiuk commented on components/Aromas/DropDown/DropDown.tsx
перейменувати на AromaDropDown i разом зі Stars винести в ui-kit

2023-11-20 13:14 UTC, nadiakhoptiuk commented
і ще такий ворнінг:
https://prnt.sc/midXLumN-Z45

2023-11-20 17:23 UTC, Bardjur commented on components/Aromas/DropDown/DropDown.tsx
> +  const cutBrackets = (title: string) => {
видалив

2023-11-20 17:24 UTC, Bardjur commented on components/Aromas/DropDown/DropDown.tsx
> +      ref={dropdownRef}
поставив падінги на кнопку

2023-11-20 17:25 UTC, Bardjur commented on components/Aromas/DropDown/DropDown.tsx
> +        <ul className="absolute left-0 top-[40px] z-10 flex flex-col bg-white shadow-dropdown smOnly:w-full">
зробив ширину кнопки і списку 100% а загальному контейнеру додав стилі

2023-11-20 17:25 UTC, Bardjur commented on components/Aromas/Aromas.tsx
> +        <span className="font-semibold">{notes} </span>
добавив

2023-11-20 17:25 UTC, Bardjur commented on components/Aromas/DropDown/DropDown.tsx
виніс в ui

2023-11-20 17:25 UTC, Bardjur commented on dictionaries/uk/product_page.json
> +    "catalog": {
пофіксив і тут

2023-11-20 17:26 UTC, Bardjur commented on components/Aromas/DropDown/DropDown.tsx
> +      </button>
якщо це за відступи між дужками то зробив

2023-11-21 10:24 UTC, nadiakhoptiuk commented
тут все ок, але злию після злиття Каталогу, як підтягнеш ті зміни (бо тут є ті файли)

2023-11-21 10:25 UTC, nadiakhoptiuk approved these changes

2023-11-21 16:45 UTC, merged