metadata generating update
SoftRyzen-internship/13candles-frontend pull request #109
Opened 2023-11-21 22:52 UTC by opanchen

- створив ф-ю createMetadata.ts для спроби реалізації генерування мета даних на сторінках в реюзабельній манері. Є певні сумніви щодо доцільності такого підходу, враховуючи ререндер і загалтне навантаження на сторінки - треба свіжий і експертний погляд зі сторони;
- перейменував хук UseWindowDimension з розширенням tsx, додав кастомним хукам директиву 'use client' щоб захендлити помилки в браузері (раніше некст не вимагав);
- в термінал почало приходити попередження про імпорти та реекспорт певних функцій (1 - повʼязано з хуками, 2 - з використанням ф-ї createMetadata.ts): https://prnt.sc/D_HDyVa87tvj Питання потребує перевірки та додаткового дослідження;

2023-11-22 14:05 UTC, nadiakhoptiuk requested changes

2023-11-22 14:05 UTC, nadiakhoptiuk commented on app/[lang]/page.tsx
> +import type { Locale } from '@/i18n.config';
локальні типи імпортуй нижче по коду, після утиліт і апішок

після next через ентер перемісти компоненти

2023-11-22 14:05 UTC, nadiakhoptiuk commented on app/[lang]/business/page.tsx
> +import type { Locale } from '@/i18n.config';
тут також типи - нижче розмістити

2023-11-22 14:06 UTC, nadiakhoptiuk commented
> * створив ф-ю createMetadata.ts для спроби реалізації генерування мета даних на сторінках в реюзабельній манері. Є певні сумніви щодо доцільності такого підходу, враховуючи ререндер і загальне навантаження на сторінки - треба свіжий і експертний погляд зі сторони;
> * перейменував хук UseWindowDimension з розширенням tsx, додав кастомним хукам директиву 'use client' щоб захендлити помилки в браузері (раніше некст не вимагав);
> * в термінал почало приходити попередження про імпорти та реекспорт певних функцій (1 - повʼязано з хуками, 2 - з використанням ф-ї createMetadata.ts): https://prnt.sc/D_HDyVa87tvj Питання потребує перевірки та додаткового дослідження;


я б все таки залишила 2 функції - одну для статики, іншу для динамічних сторінок, так буде менше коду, менше перевірок. в лейауті запускала б і отримувала дані для home
а на інших сторінках би перезаписувала, тобто запускала б ту яку потрібно (статичну для бізнесу або динамічну, яку ти створив, для динамічних сторінок), і повертала б усе, окрім: https://prnt.sc/c7ZH1jZp4Zb3

2023-11-22 20:03 UTC, opanchen commented on utils/createMetadata.ts
> +  category?: string;
ок

2023-11-22 20:03 UTC, opanchen commented on app/[lang]/page.tsx
> +import type { Locale } from '@/i18n.config';
ок

2023-11-22 20:03 UTC, opanchen commented on app/[lang]/business/page.tsx
> +import type { Locale } from '@/i18n.config';
ок

2023-11-22 20:21 UTC, opanchen commented
UPD: 
- змінено назви (розширення ts) та імпорти (без реекспорту) для кастомних хуків щоб позбутися описаної вище помилки в терміналі;
- на сторінках та лояутах з динамічними параметрами прописав `export const dynamic = 'error'` та `export const revalidate = false`;
- змінено структуру генерування метаданих: основні дані генеруються в головному лояуті, на сторінці для бізнесу перезаписуються локально, на динамічних сторінках - за допомогою утилітної ф-ї createMetadata.ts;
- для сторінок категорії та товару зберігаються дефолтні ключові слова з головного лояуту, оскільки генерувати їх динамічно надто складно, враховуючи специфіку наповнення адмін-панелі контентом;
- створено файл sitemap.ts, який генерує адреси для статичних сторінок та категорій (для генерування сторінок товарів необхідно створити додатковий graphql запит за усіма товарами або тільки за їх слагами);
- в sitemap.ts наразі окремі запити на категорії для різних мов, оскільки є сумніви, що поле slug може відрізнятись у різних версіях на стороні бекенду. Якщо з цим все ок і вони однакові, приберемо зайвий запит і оптимізуємо код;

2023-11-23 10:05 UTC, nadiakhoptiuk commented
> UPD:
> 
> * змінено назви (розширення ts) та імпорти (без реекспорту) для кастомних хуків щоб позбутися описаної вище помилки в терміналі;
> * на сторінках та лояутах з динамічними параметрами прописав `export const dynamic = 'error'` та `export const revalidate = false`;
> * змінено структуру генерування метаданих: основні дані генеруються в головному лояуті, на сторінці для бізнесу перезаписуються локально, на динамічних сторінках - за допомогою утилітної ф-ї createMetadata.ts;
> * для сторінок категорії та товару зберігаються дефолтні ключові слова з головного лояуту, оскільки генерувати їх динамічно надто складно, враховуючи специфіку наповнення адмін-панелі контентом;
> * створено файл sitemap.ts, який генерує адреси для статичних сторінок та категорій (для генерування сторінок товарів необхідно створити додатковий graphql запит за усіма товарами або тільки за їх слагами);
> * в sitemap.ts наразі окремі запити на категорії для різних мов, оскільки є сумніви, що поле slug може відрізнятись у різних версіях на стороні бекенду. Якщо з цим все ок і вони однакові, приберемо зайвий запит і оптимізуємо код;

до останнього пункту - слаги на двох мовах однакові

2023-11-23 14:36 UTC, opanchen commented
UPD:
- оновлено sitemap.ts: один запит на сервер за усіма необхідними даними => динамічна генерація необхідних обʼєктів;
- оновлено всі реквести, додано параметр `pagination: { limit: 100 }`;

2023-11-23 14:53 UTC, nadiakhoptiuk requested changes

2023-11-23 14:53 UTC, nadiakhoptiuk commented on app/[lang]/[category]/layout.tsx
> +export const dynamic = 'error';
export const revalidate = false;

додай, будь ласка

2023-11-23 14:53 UTC, nadiakhoptiuk commented on app/[lang]/sitemap.ts
> +  const locales = ['en', 'uk'];
імпортуй собі дефолтну локаль з файлу i18n, бо якщо зміняться, то зміняться там, і щоб сюди руками не йти виправляти

2023-11-23 15:03 UTC, opanchen commented on app/[lang]/[category]/layout.tsx
> +export const dynamic = 'error';
ок

2023-11-23 15:46 UTC, nadiakhoptiuk approved these changes

2023-11-23 15:47 UTC, merged