Catalog
SoftRyzen-internship/13candles-frontend pull request #11
Opened 2023-10-23 12:27 UTC by mariia-kovalova

2023-10-23 14:43 UTC, Volodymyr-Bezyk approved these changes

2023-10-24 11:57 UTC, nadiakhoptiuk requested changes

2023-10-24 11:57 UTC, nadiakhoptiuk commented on sections/home/CatalogSection/CatalogSection.tsx
> +  const title = 'Каталог';
треба винести в json для двох мов title i subtitle

2023-10-24 11:57 UTC, nadiakhoptiuk commented on types/Product.ts
цей файл помилково тут?

2023-10-24 11:57 UTC, nadiakhoptiuk commented on components/ui/ContactLink/ContactLink.tsx
> +    <a href={href} className={linkClasses}>
контакти поправити в іншому ПР і потім стягнути

2023-10-24 11:57 UTC, nadiakhoptiuk commented on components/ui/CategoryCard/CategoryCard.tsx
> +      <div className="relative mb-3 h-[148px] overflow-hidden md:h-[256px] xl:mb-5 xl:h-[224px]">
висоту для мобільного поставимо auto, як домовлялися

2023-10-24 13:44 UTC, Volodymyr-Bezyk approved these changes

2023-10-24 14:10 UTC, mariia-kovalova commented on components/ui/CategoryCard/CategoryCard.tsx
> +      <div className="relative mb-3 h-[148px] overflow-hidden md:h-[256px] xl:mb-5 xl:h-[224px]">
я зробила через калк, щоб вони залишалися як у макеті - квадратними (прохання від Андрія тестувальника)

2023-10-24 15:46 UTC, nadiakhoptiuk approved these changes

2023-10-24 15:46 UTC, merged