Feature/Business link
SoftRyzen-internship/13candles-frontend pull request #19
Opened 2023-10-24 08:43 UTC by mariia-kovalova

2023-10-24 12:10 UTC, nadiakhoptiuk requested changes

2023-10-24 12:10 UTC, nadiakhoptiuk commented on components/ui/BusinessLink/BusinessLink.tsx
> +    <Link href={href} className={linkClasses}>
якщо цей компонент суто для сторінки бізнесу, можливо одразу прописати href

потрібно створити файл routes  (можна в корені проєкту) із обєктом раутів:

HOME: /
FOR_BUSINESS: /business

і можна з dictionaries з файлу home прибрати href тоді

2023-10-24 12:10 UTC, nadiakhoptiuk commented on components/ui/BusinessLink/BusinessLink.tsx
> +    <Link href={href} className={linkClasses}>
треба продумати пропс, бо цей компонент можна буде використати у футері, але там немає іконки

2023-10-24 13:40 UTC, mariia-kovalova commented on components/ui/BusinessLink/BusinessLink.tsx
> +    <Link href={href} className={linkClasses}>
зробити перевикористовуваний NavLink?

2023-10-24 20:54 UTC, mariia-kovalova commented on components/ui/BusinessLink/BusinessLink.tsx
> +    <Link href={href} className={linkClasses}>
замерджила код Володимира, бо він також рефакторив локалізацію

2023-10-25 04:24 UTC, Volodymyr-Bezyk approved these changes

2023-10-25 08:31 UTC, Volodymyr-Bezyk approved these changes

2023-10-25 08:40 UTC, nadiakhoptiuk requested changes

2023-10-25 08:40 UTC, nadiakhoptiuk commented on data/routes.ts
> +  CATALOG: '/catalog',
каталог і about це не окремі сторінки.
в цьому файлі лише раути на сторінки повинні бути (якщо вони визначені)

2023-10-25 09:03 UTC, nadiakhoptiuk approved these changes

2023-10-25 09:03 UTC, merged