About
SoftRyzen-internship/13candles-frontend pull request #23
Opened 2023-10-25 09:28 UTC by Veronikanos

Implement About section with translated text from new jsons.

2023-10-25 10:15 UTC, Volodymyr-Bezyk approved these changes

2023-10-26 09:52 UTC, nadiakhoptiuk requested changes

2023-10-26 09:52 UTC, nadiakhoptiuk commented on sections/home/AboutSection/AboutSection.tsx
> +        <ul className="flex-1 text-justify md:m-auto md:leading-[19px] xl:text-lg smOnly:mb-6">
по семантиці це не список, це просто текст із абзацами, скоріше div і треба p повертати

на моб відступ вниз від цього блока 32

2023-10-26 10:17 UTC, Veronikanos commented on sections/home/AboutSection/AboutSection.tsx
> +      <h2 className="section-title-primary md:mb-6 smOnly:mb-3">
Виправлено.

2023-10-26 10:22 UTC, Veronikanos commented on sections/home/AboutSection/AboutSection.tsx
> +        <ul className="flex-1 text-justify md:m-auto md:leading-[19px] xl:text-lg smOnly:mb-6">
Виправлено.

2023-10-26 10:26 UTC, Veronikanos commented on sections/home/AboutSection/AboutSection.tsx
> +            <li key={i} className="mb-3 last:mb-0 last:tracking-[-0.16px]">
Виправлено. Також обмежена ширина блоку тексту згідно макету.

2023-10-26 10:35 UTC, Veronikanos commented on sections/home/AboutSection/AboutSection.tsx
> +      <Button
Виправлено.

2023-10-26 10:35 UTC, Veronikanos commented on app/[lang]/page.tsx
> +        <AboutSection about={about} />
Виправлено.

2023-10-26 10:42 UTC, Veronikanos commented on sections/home/AboutSection/AboutSection.tsx
> +      <div className="gap-8 md:mb-8 md:flex xl:mx-auto xl:mb-12 xl:max-w-5xl xl:gap-[132px] mdOnly:gap-[30px]">
Якщо поставлю 32, то через 1 піксель слово переноситься на новий рядок. Можу зробити 31 px, щоб виглядало нормально.
![image](https://github.com/SoftRyzen-internship/13candles-frontend/assets/49239848/77a48374-8d26-4484-8a2a-b63d82126bcb)

2023-10-26 10:50 UTC, Veronikanos commented on sections/home/AboutSection/AboutSection.tsx
> +            width={500}
Виправлено.

2023-10-26 12:16 UTC, nadiakhoptiuk approved these changes

2023-10-26 12:16 UTC, merged