Feat/Socials
SoftRyzen-internship/13candles-frontend pull request #25
Opened 2023-10-25 12:36 UTC by Veronikanos

Add socials menu with links

![image](https://github.com/SoftRyzen-internship/13candles-frontend/assets/49239848/2068c474-1b73-477f-a7ff-b2e19d60c39d)

Fix width in TranslationSwitcher link.

2023-10-25 13:22 UTC, Volodymyr-Bezyk approved these changes

2023-10-25 20:25 UTC, nadiakhoptiuk requested changes

2023-10-25 20:25 UTC, nadiakhoptiuk commented on components/Header/Header.tsx
> +  console.log(sidePanelMenu);
прибрати логи,  якщо вже не потрібні

2023-10-25 20:25 UTC, nadiakhoptiuk commented on components/Header/Header.tsx
> +import { HeaderProps } from '@/types/HeaderProps';
пропси будемо писати у кожній папці компонента, а загальні - уже в @/types

2023-10-25 20:26 UTC, nadiakhoptiuk commented
хедер поки не завершений.. наразі правки:

перемістити хедер в папку layout і підключити в layout.tsx

2023-10-26 07:12 UTC, Veronikanos commented on components/Header/Header.tsx
> +  console.log(sidePanelMenu);
Компонент хедера прибрала взагалі, він буде окремою гілкою.

2023-10-26 07:13 UTC, Veronikanos commented on components/Header/Header.tsx
> +import { HeaderProps } from '@/types/HeaderProps';
Компонент хедера прибрала взагалі, він буде окремою гілкою.

2023-10-26 07:18 UTC, Veronikanos commented on components/Header/Header.tsx
> +import { HeaderProps } from '@/types/HeaderProps';
Запушився випадково з цією гілкою недороблений.

2023-10-26 08:25 UTC, nadiakhoptiuk approved these changes

2023-10-26 08:26 UTC, merged