I18n setup
SoftRyzen-internship/13candles-frontend pull request #6
Opened 2023-10-20 14:17 UTC by Veronikanos

- Implement Internationalization with i18n and next-intl.
- Add TranslationExample to show how it works.
- Describe usage in README.md

2023-10-20 16:38 UTC, Volodymyr-Bezyk approved these changes

2023-10-23 13:33 UTC, nadiakhoptiuk requested changes

2023-10-23 13:33 UTC, nadiakhoptiuk commented on messages/en/home.json
папку messages краще назвати dictionaries, бо не дуже зрозуміло, що це

2023-10-23 13:33 UTC, nadiakhoptiuk commented on messages/en/login.json
тільки сторінку login перейменувати на bussiness, + ще потім додамо файл common для спільних (хедер/футер)

2023-10-23 13:48 UTC, merged

2023-10-23 14:10 UTC, Veronikanos commented on messages/en/login.json
Сторінки логіну немає, це просто мокап для візуалізації роботи кнопки-перемикача мови. Лишні файли будуть видалені.

2023-10-23 14:19 UTC, Veronikanos commented on messages/en/home.json
Змінила в PR №12