Contacts list, read me
SoftRyzen-internship/13candles-frontend pull request #8
Opened 2023-10-23 07:32 UTC by mariia-kovalova

2023-10-23 09:51 UTC, Volodymyr-Bezyk approved these changes

2023-10-24 09:25 UTC, nadiakhoptiuk requested changes

2023-10-24 09:25 UTC, nadiakhoptiuk commented on components/ui/ContactLink/ContactLink.tsx
> +  className,
тут також додати пустий рядок

2023-10-24 09:32 UTC, nadiakhoptiuk commented
отут ще бажано пофіксити вигляд при фокусуванні https://prnt.sc/jDL2QaPhOG6o

2023-10-24 11:11 UTC, mariia-kovalova commented on components/ContactList/ContactList.tsx
> +const links = [
винесемо в dictionaries як буде готова локілізація

2023-10-24 11:12 UTC, mariia-kovalova commented on components/ui/ContactLink/ContactLink.tsx
> +    <a href={href} className={linkClasses}>
тоді цей компонент можна перевикористати, добре))

2023-10-24 13:49 UTC, Volodymyr-Bezyk approved these changes

2023-10-24 15:06 UTC, nadiakhoptiuk approved these changes

2023-10-24 15:39 UTC, merged