dropdown initial commit
SoftRyzen-internship/13candles-frontend pull request #90
Opened 2023-11-14 19:33 UTC by opanchen

- створено окремий компонент випадаючого списку;
- дизайн компонента реалізовано відповідно до макету, від себе додав дефолтний ховер/фокус для лінків - окремі питання стосовно ховеру/фокусу та інших нюансів, що не представлено в макеті чи ТЗ, пропоную прокомунікувати під час стендапу чи з дизайнером індивідуально;
- лейбл "Категорії" для кнопки визначається локально всередині компонента залежно від поточної мови (рядок 44 CategoriesDropdown.tsx) - рішення тимчасове, поки не буде прописано окремо в json-файлі;
- рядок 60 CategoriesDropdown.tsx закоментовано, оскільки немає на макеті - розкоментую або видалю після узгодження;
- структура та стилі page.tsx для даного динамічного роуту абстрактні/довільні, щоб відобразити розташування дропдауну - наскільки розумію, сторінка з секцією буде реалізовуватись окремо;

2023-11-15 13:19 UTC, nadiakhoptiuk requested changes

2023-11-15 13:19 UTC, nadiakhoptiuk commented on components/CategoriesDropdown/CategoriesDropdown.tsx
> +    return title.includes('(') ? title.slice(0, title.indexOf('(')) : title;
тут треба також обрізати, якщо назва довга "..."


додати через css

overflow: hidden;
white-space: nowrap;
text-overflow: ellipsis;

2023-11-15 13:19 UTC, nadiakhoptiuk commented on components/CategoriesDropdown/CategoriesDropdown.tsx
> +  const label = lang === 'en' ? 'Categories' : 'Категорії';
тут, як домовлялись - в json

2023-11-15 13:19 UTC, nadiakhoptiuk commented on components/CategoriesDropdown/CategoriesDropdown.tsx
> +          //   className={isOpen ? 'rotate-180' : ''}
rotate зайвим не буде, думаю)

2023-11-15 13:19 UTC, nadiakhoptiuk commented on components/CategoriesDropdown/CategoriesDropdown.tsx
> +                className={`block px-[16px] py-[12px] text-center hover:bg-[#EBEBEB] focus:bg-[#EBEBEB] md:text-left ${
кольори треба виносити в tailwind.config, якщо їх там немає

2023-11-15 13:19 UTC, nadiakhoptiuk commented on components/CategoriesDropdown/CategoriesDropdown.tsx
> +                  currentCategory === slug && 'pointer-events-none bg-[#EBEBEB]'
тут прописати через тернарник і повертати пустий рядок, бо повертає "false" у рядку класів, або через лібу classNames додавати класи

2023-11-15 16:01 UTC, opanchen commented on components/CategoriesDropdown/CategoriesDropdown.tsx
> +    return title.includes('(') ? title.slice(0, title.indexOf('(')) : title;
+

2023-11-15 16:01 UTC, opanchen commented on components/CategoriesDropdown/CategoriesDropdown.tsx
> +  const label = lang === 'en' ? 'Categories' : 'Категорії';
+

2023-11-15 16:02 UTC, opanchen commented on components/CategoriesDropdown/CategoriesDropdown.tsx
> +          //   className={isOpen ? 'rotate-180' : ''}
ок

2023-11-15 16:02 UTC, opanchen commented on components/CategoriesDropdown/CategoriesDropdown.tsx
> +                className={`block px-[16px] py-[12px] text-center hover:bg-[#EBEBEB] focus:bg-[#EBEBEB] md:text-left ${
ок

2023-11-15 16:02 UTC, opanchen commented on components/CategoriesDropdown/CategoriesDropdown.tsx
> +                  currentCategory === slug && 'pointer-events-none bg-[#EBEBEB]'
ок

2023-11-16 09:00 UTC, nadiakhoptiuk approved these changes

2023-11-16 09:02 UTC, merged