fixed footer for different pages
SoftRyzen-internship/13candles-frontend pull request #91
Opened 2023-11-14 22:51 UTC by Bardjur

2023-11-15 08:55 UTC, nadiakhoptiuk requested changes

2023-11-15 08:55 UTC, nadiakhoptiuk commented on layout/Footer/Footer.tsx
> +
тут можна використати функцію 
import { checkPageName } from '@/utils';
і якщо це сторінка home то показуємо FooterNavRow

у репо в пошуку глянь, як її використовували

2023-11-15 08:55 UTC, nadiakhoptiuk commented on layout/Footer/Footer.tsx
> +import { usePathname } from 'next/navigation';
усі віддалені імпорти розміщуємо вгорі по коду

2023-11-15 11:29 UTC, Bardjur commented on layout/Footer/Footer.tsx
> +
переніс

2023-11-15 11:29 UTC, Bardjur commented on layout/Footer/Footer.tsx
> +import { usePathname } from 'next/navigation';
переніс на початок

2023-11-16 09:34 UTC, nadiakhoptiuk approved these changes

2023-11-16 09:43 UTC, merged