created product slider & fixed bug at home page
SoftRyzen-internship/13candles-frontend pull request #92
Opened 2023-11-15 14:58 UTC by opanchen

- реалізовано слайдер для сторінки товару з перевикористанням існуючого компонента Slider.tsx;
- додано логіку збереження інтерактивності слайдера (за виключенням навігаційних кнопок) у випадку наявності лише 1 зображення, відповідно до ТЗ;
- виправлено баг на головній сторінці шляхом додавання верхнього падінгу для секції "Каталог" (пункт 8 ТЗ);

2023-11-16 10:14 UTC, nadiakhoptiuk requested changes
також потрібно додати властивість, щоб попередньо завантажувався 1 слайд справа і зліва, у компонент Slider (lazyLoadPrevNext, якось так, пошукай будь ласка..)

2023-11-16 10:14 UTC, nadiakhoptiuk commented on components/ui/ProductImage/ProductImage.tsx
> +      width={680}
652 х 650 за макетом

2023-11-16 10:14 UTC, nadiakhoptiuk commented on components/ui/ProductImage/types.ts
> +  photo: { data: { attributes: { url: string } } };
цей тип є в types/commons.ts

2023-11-16 10:14 UTC, nadiakhoptiuk commented on components/ui/ProductImage/ProductImage.tsx
> +import Image from 'next/image';
віддалені імпорти завжди вище по коду

2023-11-16 10:14 UTC, nadiakhoptiuk commented on components/ProductSlider/ProductSlider.tsx
> +  const slides = images.length > 1 ? images : [...images, ...images]; // to keep slider interactive in the case of 1 available slide
ми вимикаємо навігацію коли зображення одне, тоді навіщо прокидувати масив із двох зображень?
виходить, навігація вимкнена, а зображень 2. і вони свайпаються..

краще тут повертати те, що є по факту, одне то одне

2023-11-16 14:40 UTC, opanchen commented on components/ui/ProductImage/ProductImage.tsx
> +      width={680}
ок

2023-11-16 14:40 UTC, opanchen commented on components/ui/ProductImage/types.ts
> +  photo: { data: { attributes: { url: string } } };
ок, імпортував напряму в компонент

2023-11-16 14:40 UTC, opanchen commented on components/ui/ProductImage/ProductImage.tsx
> +import Image from 'next/image';
ок

2023-11-16 14:41 UTC, opanchen commented on components/ProductSlider/ProductSlider.tsx
> +  const slides = images.length > 1 ? images : [...images, ...images]; // to keep slider interactive in the case of 1 available slide
збило з пантелику тз, перемудрив - виправлено

2023-11-17 11:04 UTC, nadiakhoptiuk approved these changes

2023-11-17 11:12 UTC, merged