updated basket modal
SoftRyzen-internship/13candles-frontend pull request #95
Opened 2023-11-16 13:59 UTC by opanchen

- оновлено логіку компонента Basket.tsx: 
1. якщо пропсом передають назву (з кнопки кошику в хедері, наприклад), саме ця назва використовується в компоненті - інакше використовується дефолтна назва зі статичного словника, який підтягується асинхронно;
2. залежно від значення selectedProps відбувається рендер дефолтного повідомлення або компонентів оформлення замовлення (будуть реалізовані в майбутньому);
- додатково прибрав  локальний колір з компонента CategoriesDropdown.tsx - він наслідується автоматично і відповідає макету;

2023-11-16 14:21 UTC, nadiakhoptiuk requested changes

2023-11-16 14:21 UTC, nadiakhoptiuk commented on dictionaries/en/common.json
> +      "title": "Оформлення замовлення",
змінити на англійську

2023-11-16 14:52 UTC, opanchen commented
> > * оновлено логіку компонента Basket.tsx:
> > 
> > 
> > 1. якщо пропсом передають назву (з кнопки кошику в хедері, наприклад), саме ця назва використовується в компоненті - інакше використовується дефолтна назва зі статичного словника, який підтягується асинхронно;
> > 2. залежно від значення selectedProps відбувається рендер дефолтного повідомлення або компонентів оформлення замовлення (будуть реалізовані в майбутньому);
> > 
> > 
> > * додатково прибрав  локальний колір з компонента CategoriesDropdown.tsx - він наслідується автоматично і відповідає макету;
> 
> яким чином в пункті 2 буде забезпечена локалізація?

допускаю, що статичний текстовий контент в форму та елемент списку ("Ваше замовлення") передаватиметься пропсами з Basket.tsx, а динамічні дані (назва товару, аромат і тд) - з глобального стейту. В даному випадку змінна selectedProducts використовується для відображення рендеру по умові залежно від майбутнього стейту в зустанд.

2023-11-16 15:01 UTC, opanchen commented on dictionaries/en/common.json
> +      "title": "Оформлення замовлення",
ok

2023-11-17 16:56 UTC, nadiakhoptiuk approved these changes

2023-11-18 08:19 UTC, merged