Feature/counter
SoftRyzen-internship/13candles-frontend pull request #96
Opened 2023-11-17 08:09 UTC by Bardjur

видалив попередній пул реквест, зробив з гілки dev, виправив недоліки. Прийшлось зменшити по 4px іконки щоб не міняти розмір блоку і щоб вміщалось 2 числа

2023-11-17 11:43 UTC, nadiakhoptiuk requested changes

2023-11-17 11:43 UTC, nadiakhoptiuk commented on components/ui/Counter/Counter.tsx
> +            <MinusSmIcon width={20} height={20} />
24 це самий мінімальний розмір кнопки, не варто зменшувати, бо складно попасти пальцем ітак, краще розширити div (зробити йому мінімальну ширину, і ширину max-content), тим більше, що місце є щоб розширити

2023-11-17 13:58 UTC, Bardjur commented on components/ui/Counter/Counter.tsx
> +            <MinusSmIcon width={20} height={20} />
зробив

2023-11-20 09:39 UTC, nadiakhoptiuk approved these changes

2023-11-20 09:40 UTC, merged