init store, created AddToCartBtn.tsx & updated basket-components
SoftRyzen-internship/13candles-frontend pull request #99
Opened 2023-11-19 00:47 UTC by opanchen

- створено початкову версію zustand-стору з персистом в session storage та ручною гідрацією (повʼязано зі специфікою персисту в Next.js, поки реалізовано через кастомний хук useRehydrate(), можливе допрацювання);
- оновлено компонент BasketButton.tsx: 
1. залежно від пропсів він рендерить кнопку-іконку кошика, кнопку-текст кошика (для десктопного футера) або кнопку "Оформити покупку";
2. компонент підписаний на стор - при наявності доданих товарів над іконкою кошика зʼявляється елемент з їх кількістю;
3. локалізацію реалізовано шляхом прокидання пропсів від лояуту/сторінки до кнопки з подальшою передачею в модалку;
- створено компонент FakeProductCard.tsx - чорновий варіант майбутньої секцію для схематичного позиціонування елементів, операцій з внутрішнім та глобальним стейтом - пізніше буде видалено;
- в модалці кошика схематично показано список обраних товарів для візуалізації роботи стору та тесту функції видалення товарів;

2023-11-20 09:47 UTC, opanchen commented
- змінено налаштування персисту стору на local storage;

2023-11-20 13:58 UTC, nadiakhoptiuk requested changes

2023-11-20 13:58 UTC, nadiakhoptiuk commented on app/[lang]/[category]/[product]/page.tsx
> +                  {/*
цей код можна було б одразу видалити

2023-11-20 13:58 UTC, nadiakhoptiuk commented on components/Basket/Basket.tsx
> +                      {orderCard.aromaText} {aroma}{' '}
{' '} треба прибирати в даному випадку

2023-11-20 13:58 UTC, nadiakhoptiuk commented on components/Basket/Basket.tsx
> +                  {aroma && (
розбивай, будь ласка, код ентерами, де це можливо, де йдуть теги і вирази jsx, так читабельніше

2023-11-20 13:58 UTC, nadiakhoptiuk commented on components/ui/BasketButton/BasketButton.tsx
>        {isIcon ? (
не використовуй довгі тернарники, де більше двох кейсів, це нечитабельно і складно. 
можна навіть написати рендер за умови з допомогою && (3 випадки)

2023-11-20 13:58 UTC, nadiakhoptiuk commented on store/store.ts
> +                ({ product: { title, aroma } }) =>
свариться type script

2023-11-20 13:58 UTC, nadiakhoptiuk commented on store/store.ts
> +              ({ product }) =>
свариться type script

2023-11-20 14:50 UTC, opanchen commented on app/[lang]/[category]/[product]/page.tsx
> +                  {/*
ок

2023-11-20 14:50 UTC, opanchen commented on components/Basket/Basket.tsx
> +                  {aroma && (
ок

2023-11-20 14:51 UTC, opanchen commented on components/Basket/Basket.tsx
> +                      {orderCard.aromaText} {aroma}{' '}
ок

2023-11-20 14:51 UTC, opanchen commented on components/ui/BasketButton/BasketButton.tsx
>        {isIcon ? (
замінив на рендер за умовою &&

2023-11-20 14:52 UTC, opanchen commented on store/store.ts
> +                ({ product: { title, aroma } }) =>
відповів в особисті, ймовірно баг лінтера в редакторі коду

2023-11-20 14:53 UTC, opanchen commented on store/store.ts
> +              ({ product }) =>
відповів в особисті, можливо впливають загаліні налаштування tsconfig.json

2023-11-21 10:29 UTC, nadiakhoptiuk approved these changes

2023-11-21 10:31 UTC, merged